apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: bln2z5nja-python
  janus-idp.io/tekton: bln2z5nja-python
  backstage.io/kubernetes-id: bln2z5nja-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: bln2z5nja-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
