apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: bln2z5nja-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: bln2z5nja-python 
  name: bln2z5nja-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: bln2z5nja-python 
