apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: bln2z5nja-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-python:9876e90f6ddd585d4fd1b46b616d3b70815bc906@sha256:6fb4c50fe71d63bdeda3f133806b73eb3521370c3fd50943747f0b491ae740a5
          name: container-image
